### PR TITLE
Added Russian

### PR DESCRIPTION
**Pull request by rellikmil**

### CODE REVIEW

**Comment by jorio** [comment]
Cool! I'll add Cyrillic support to the game's fonts and I'll let you know when it's ready.

**Comment by rellikmil** [comment]
I think that you rip Russian font from localization, or you gonna draw fonts from scratch?

20 июня 2024 г. 00:47:49 GMT+03:00, Iliyas Jorio ***@***.***> пишет:

**Comment by jorio** [comment]
I've redrawn the missing glyphs. Please let me know if anything looks off.

cyrillicsampletext

**Comment by rellikmil** [comment]
hq720
Looks godlike, indeed godlike. Your version is better, than in localization. Д, И, and Л look the way they should.
изображение
изображение
изображение

**Comment by jorio** [comment]
Awesome! Thanks for your feedback.

**Pull request merged**
